-- 001_initial_schema.down.sql
BEGIN;

DROP TABLE IF EXISTS edits CASCADE;
DROP TABLE IF EXISTS renders CASCADE;
DROP TABLE IF EXISTS generations CASCADE;
DROP TABLE IF EXISTS timelines CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS schema_migrations CASCADE;

COMMIT;
